### PR TITLE
Facebook Bussiness Login config_id added

### PR DESCRIPTION
**Pull request by narayanmettle**
I have added a config_id for the facebook login for the business type login

### CODE REVIEW

**Review by cuongdevjs — COMMENTED** [review]
why do you remove dist in gitignore?

**Comment by narayanmettle** [comment]
That I have used for internal uses and forgot to revert it back.

**Comment by cuongdevjs** [comment]
please remove unnecessary changed files and follow the file format. There are some redundant commits, although I appreciate your contribution but this doesn't guarantee the code standard.

**Comment by narayanmettle** [comment]
Once I remove the other commits rather than the config_id change hope it’s
good to go for the pull merge. What do you think? We need the solution.

**Comment by cuongdevjs** [comment]
yep, please create a new PR with only the necessary changed file, and make sure you follow the formatting code that currently it has. Thank you.

**Comment by narayanmettle** [comment]
Okay, thank you! I will do that and please merge that request. Thanks again

**Pull request closed without merging**
